source /etc/profile.d/vte-*.sh
source /usr/share/antigen.zsh

antigen use oh-my-zsh

antigen bundle golang
antigen bundle rake-fast
antigen bundle screen
antigen bundle sudo

antigen bundle mollifier/anyframe
antigen bundle zsh-users/zsh-syntax-highlighting

antigen apply

PROMPT=$'%(!.%{$fg_bold[red]%}.%{$fg_bold[green]%}%n@)%m %{$fg_bold[blue]%}%(!.%1~.%~)%{$reset_color%} $(git_prompt_info)\n%{$fg_bold[blue]%}$%{$reset_color%} '
ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg[green]%}("

setopt hist_ignore_all_dups
unsetopt correct_all

export PATH=$HOME/bin:$HOME/.anyenv/bin:$HOME/.yarn/bin:$HOME/.cargo/bin:$HOME/.local/bin:$HOME/.heroku-cli/bin:$PATH
export GOPATH=$HOME
unset RUBYOPT

which anyenv 2>&1 > /dev/null && eval "$(anyenv init -)"
which direnv 2>&1 > /dev/null && eval "$(direnv hook zsh)"

autoload -Uz chpwd_recent_dirs cdr add-zsh-hook
add-zsh-hook chpwd chpwd_recent_dirs

autoload -Uz zmv
alias zmv='noglob zmv -W'

bindkey '^[d' anyframe-widget-cdr
bindkey '^[g' anyframe-widget-cd-ghq-repository
bindkey '^[r' anyframe-widget-execute-history

alias be='bundle exec'
alias g='git'
alias open='xdg-open'
alias dc='docker-compose'

for i in .google-cloud-sdk/{path,completion}.zsh.inc .local/bin/eb_completion.bash .travis/travis.sh; do
  [ -f $HOME/$i ] && source $HOME/$i
done
