source /usr/share/antigen.zsh

antigen use oh-my-zsh

antigen bundle golang
antigen bundle rake-fast
antigen bundle screen
antigen bundle sudo

antigen bundle mollifier/anyframe
antigen bundle zsh-users/zsh-syntax-highlighting

antigen apply

PROMPT=$'%(!.%{$fg_bold[red]%}.%{$fg_bold[green]%}%n@)%m %{$fg_bold[blue]%}%(!.%1~.%~)%{$reset_color%} $(git_prompt_info)\n%{$fg_bold[blue]%}$%{$reset_color%} '
ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg[green]%}("

setopt hist_ignore_all_dups
unsetopt correct_all

export PATH=$HOME/bin:$HOME/.cargo/bin:$HOME/.anyenv/bin:$PATH
export GOPATH=$HOME
unset RUBYOPT

eval "$(anyenv init -)"
eval "$(direnv hook zsh)"

autoload -Uz chpwd_recent_dirs cdr add-zsh-hook
add-zsh-hook chpwd chpwd_recent_dirs

autoload -Uz zmv
alias zmv='noglob zmv -W'

bindkey '^[d' anyframe-widget-cdr
bindkey '^[g' anyframe-widget-cd-ghq-repository
bindkey '^[r' anyframe-widget-execute-history

alias be="bundle exec"
alias g="git"
alias o="xdg-open"

# added by travis gem
[ -f /home/ursm/.travis/travis.sh ] && source /home/ursm/.travis/travis.sh
