#!/bin/sh

if [ ! -e $HOME/.vim/bundle/Vundle.vim ]; then
	git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
fi

vim -c VundleInstall -c quitall

if [ ! -e $HOME/.nodebrew ]; then
	curl -L https://git.io/nodebrew | perl - setup
fi
