(define toolbar-show-action-based-switcher-button? #f)
(define imsw-coverage 'system-global)
(define toolbar-show-switcher-button? #f)
(define toolbar-show-pref-button? #f)
(define toolbar-show-dict-button? #f)
(define toolbar-show-input-pad-button? #f)
(define toolbar-show-handwriting-input-pad-button? #f)
(define toolbar-show-help-button? #f)
(define skk-widgets '(widget_skk_input_mode))
(define default-widget_skk_input_mode 'action_skk_latin)
(define skk-input-mode-actions '(action_skk_latin action_skk_hiragana action_skk_katakana action_skk_hankana action_skk_wide_latin))
(define default-widget_skk_kana_input_method 'action_skk_roma)
(define skk-kana-input-method-actions '(action_skk_roma action_skk_azik))
