(define tutcode-on-key '("<Control>\\" generic-on-key))
(define tutcode-on-key? (make-key-predicate '("<Control>\\" generic-on-key?)))
(define tutcode-off-key '("<Control>\\" generic-off-key))
(define tutcode-off-key? (make-key-predicate '("<Control>\\" generic-off-key?)))
(define tutcode-kana-toggle-key '("<IgnoreShift>'"))
(define tutcode-kana-toggle-key? (make-key-predicate '("<IgnoreShift>'")))
(define tutcode-kigou-toggle-key '("<IgnoreShift><Control>_"))
(define tutcode-kigou-toggle-key? (make-key-predicate '("<IgnoreShift><Control>_")))
(define tutcode-mazegaki-start-sequence "alj")
(define tutcode-bushu-start-sequence "ala")
(define tutcode-latin-conv-start-sequence "al/")
(define tutcode-stroke-help-toggle-key '("<Control>/"))
(define tutcode-stroke-help-toggle-key? (make-key-predicate '("<Control>/")))
(define tutcode-begin-conv-key '(generic-begin-conv-key))
(define tutcode-begin-conv-key? (make-key-predicate '(generic-begin-conv-key?)))
(define tutcode-commit-key '(generic-commit-key))
(define tutcode-commit-key? (make-key-predicate '(generic-commit-key?)))
(define tutcode-cancel-key '("<IgnoreCase><Control>u" generic-cancel-key))
(define tutcode-cancel-key? (make-key-predicate '("<IgnoreCase><Control>u" generic-cancel-key?)))
(define tutcode-next-candidate-key '(generic-next-candidate-key))
(define tutcode-next-candidate-key? (make-key-predicate '(generic-next-candidate-key?)))
(define tutcode-prev-candidate-key '("delete" generic-prev-candidate-key))
(define tutcode-prev-candidate-key? (make-key-predicate '("delete" generic-prev-candidate-key?)))
