- file: path={{ansible_env.HOME}}/src/github.com/esminc state=directory
- git: repo=https://github.com/esminc/esm-overlay.git dest={{ansible_env.HOME}}/src/github.com/esminc/esm-overlay

- block:
  - file: dest=/etc/portage/repos.conf state=directory
  - template: src=esm.conf.j2 dest=/etc/portage/repos.conf/esm.conf mode=0644
  become: true
