- include: base.yml

- hosts: localhost
  become: true
  roles:
    - efi_stub
    - max_user_watches
    - nss-mdns
    - portage
    - use_tempaddr

- hosts: localhost
  roles:
    - anyenv
    - esm-overlay
    - google-cloud-sdk
    - heroku-client
    - vundle
    - yarn
