- include: base.yml

- hosts: localhost
  sudo: yes
  vars:
    overlays:
      bronislav: https://raw.githubusercontent.com/bronislav/overlays/master/layman.xml
  tasks:
    - include: tasks/efi_stub.yml
    - include: tasks/ipv6_privacy_extensions.yml
    - include: tasks/portage.yml

- hosts: localhost
  sudo: no
  tasks:
    - include: tasks/anyenv.yml
    - include: tasks/esm-overlay.yml
