- import_playbook: base.yml

- hosts: localhost
  become: true
  roles:
    - efi_stub
    - max_user_watches
    - use_tempaddr

- hosts: localhost
  roles:
    - anyenv
    - esm-overlay
    - google-cloud-sdk
    - heroku-client
    - vim-plug
    - yarn
