- include: base.yml

- hosts: localhost
  become: yes
  vars:
    overlays:
      bronislav: https://raw.githubusercontent.com/bronislav/overlays/master/layman.xml
  tasks:
    - include: tasks/efi_stub.yml
    - include: tasks/portage.yml
    - include: tasks/use_tempaddr.yml

- hosts: localhost
  tasks:
    - include: tasks/anyenv.yml
    - include: tasks/esm-overlay.yml
    - include: tasks/vundle.yml
