- include: base.yml

- hosts: localhost
  become: true
  vars:
    overlays:
      bronislav: https://raw.githubusercontent.com/bronislav/overlays/master/layman.xml
  roles:
    - efi_stub
    - max_user_watches
    - portage
    - use_tempaddr

- hosts: localhost
  roles:
    - anyenv
    - esm-overlay
    - google-cloud-sdk
    - heroku-client
    - vundle
    - yarn
